# Site settings
title: NAUGHTY CHEN
header-img: "images/Stormstout_Brewery.jpg"
tagline: "陈熊猫"  
description: "One Thing at a Time"  
baseurl: ""
url: "http://paaandachen.github.io/"  
#url: "http://localhost:4000"

# About/contact
owner: 
  name: "PandaChen"
  email: pandachen0611 at gmail dot com
  bio: "别急，正在酿……"

# Data
gavatar: http://dreamofbook.qiniudn.com/Az..png
favicon: images/favicon.ico

github_username: PaaandaChen  
#weibo_username: --貓ooo  
#zhihu_username: chen-xiong-mao-58  

# Build settings  
# use Github Flavored Markdown !important  
# document: http://jekyllrb.com/docs/configuration/#kramdown  
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

gems: [jekyll-paginate]
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Title


# Defaults for posts
defaults:
  -
    scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "PandaChen"
      header-img: "images/default.jpg" # We don't want posts without a header image, that whould mean white on white

# Comments 
comments :
  provider : duoshuo
  duoshuo :
    short_name : Panda
  disqus :
      short_name : Panda

# Analytics and webmaster tools stuff goes here
google_analytics: UA-72359418-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in footer navigation